#!/usr/bin/env bash
# War Thunder macOS: restore nest + unpack aces/CEF from shipped zips.
# Not a crack/recode. Unzip keeps Gaijin signatures — resign is NOT the normal fix.
#
# Order:
#   1. Restore nest if missing / .work   (clears OS Error 259)
#   2. Unpack aces + CEF if missing
#   3. Ad-hoc sign ONLY if codesign --verify fails (usually skip)
#   4. Human: Privacy & Security -> Open Anyway if blocked
#
# Do not: reinstall-loop; move nest out; blind force-sign; Done on 16KB launcher.
#
# Usage:
#   ./fix-warthunder-mac.sh
#   ./fix-warthunder-mac.sh "/path/to/Steam/steamapps/common/War Thunder"
#

set -euo pipefail

die() {
  echo "ERROR: $*" >&2
  exit 1
}

require_cmds() {
  local missing=()
  local cmd
  for cmd in "$@"; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      missing+=("$cmd")
    fi
  done
  if ((${#missing[@]})); then
    die "required program(s) not found: ${missing[*]}
Install the missing tools (Xcode CLT / macOS unzip+codesign are normally present) and re-run."
  fi
}

# Conservative signature check only — avoid codesign --deep here (can recurse
# into huge trees / odd nest layouts and isn't needed for per-binary gates).
needs_adhoc_sign() {
  local target="$1"
  [[ -e "$target" ]] || return 1
  if codesign --verify --quiet "$target" 2>/dev/null; then
    return 1
  fi
  return 0
}

unzip_into() {
  local zip="$1"
  local dest="$2"
  [[ -f "$zip" ]] || die "required zip not found:
  $zip
Is the War Thunder install incomplete, or is the game folder path wrong?"
  mkdir -p "$dest"
  if ! unzip -oq "$zip" -d "$dest"; then
    die "unzip failed for:
  $zip
  -> $dest"
  fi
}

# Pull Steam library roots from libraryfolders.vdf (tolerant of spacing).
# Unusual/custom VDF quirks may still need a manual path argument.
steam_library_paths_from_vdf() {
  local vdf="$1"
  [[ -f "$vdf" ]] || return 0
  # Match "path"   "..." with flexible whitespace; keep path as captured group 1.
  grep -E '"path"[[:space:]]+"[^"]+"' "$vdf" 2>/dev/null \
    | sed -E 's/^.*"path"[[:space:]]+"([^"]+)".*$/\1/' \
    | sed 's/\\\\/\//g' \
    || true
}

find_wt_dir() {
  local candidates=("$HOME/Library/Application Support/Steam/steamapps/common/War Thunder")
  local vdf path
  for vdf in \
    "$HOME/Library/Application Support/Steam/steamapps/libraryfolders.vdf" \
    "$HOME/Library/Application Support/Steam/config/libraryfolders.vdf"
  do
    while IFS= read -r path; do
      [[ -n "$path" ]] || continue
      candidates+=("$path/steamapps/common/War Thunder")
    done < <(steam_library_paths_from_vdf "$vdf")
  done

  local c
  for c in "${candidates[@]}"; do
    if [[ -d "$c" ]]; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

backup_then_mv() {
  local src="$1"
  local dest="$2"
  local label="$3"
  local backup_root stamp undo

  stamp="$(date +%Y%m%d-%H%M%S)"
  backup_root="$BASE/.wt-fix-backup/$stamp"
  mkdir -p "$backup_root"
  undo="$backup_root/UNDO_NEST_RESTORE.sh"

  cat >"$undo" <<UNDOF
#!/bin/bash
# Generated by fix-warthunder-mac.sh — reverses one nest restore move.
set -euo pipefail
if [[ ! -d "$dest" ]]; then
  echo "Nothing at: $dest"
  exit 1
fi
mkdir -p "$(dirname "$src")"
mv "$dest" "$src"
echo "Restored nest source to: $src"
UNDOF
  chmod +x "$undo"

  echo "About to move nest into place:"
  echo "  $src"
  echo "  -> $dest"
  echo "Undo script (no full-tree copy; avoids duplicating ~80GB):"
  echo "  $undo"

  # Optional full copy for cautious users with free disk: WT_FIX_BACKUP=1
  if [[ "${WT_FIX_BACKUP:-}" == "1" ]]; then
    echo "WT_FIX_BACKUP=1 set — copying full tree first (needs lots of free disk)..."
    cp -a "$src" "$backup_root/$label"
    echo "Full backup at: $backup_root/$label"
  fi

  if [[ -t 0 && "${WT_FIX_YES:-}" != "1" ]]; then
    read -r -p "Proceed with move? [y/N] " ans
    case "$ans" in
      y|Y|yes|YES) ;;
      *) die "aborted before nest move (nothing changed)." ;;
    esac
  fi

  mkdir -p "$(dirname "$dest")"
  mv "$src" "$dest"
  echo "Nest move done."
}

require_cmds unzip codesign grep sed mv mkdir cp chmod mktemp date dirname

BASE="${1:-}"
if [[ -z "$BASE" ]]; then
  BASE="$(find_wt_dir || true)"
fi

if [[ -z "$BASE" || ! -d "$BASE" ]]; then
  echo "Could not find your War Thunder install directory automatically."
  echo "Usage: $0 \"/path/to/Steam/steamapps/common/War Thunder\""
  exit 1
fi

LAUNCHER="$BASE/WarThunderLauncher.app"
INNER="$LAUNCHER/Contents/WarThunder.app"
GAME="$INNER/Contents/Resources/game"

echo "War Thunder dir: $BASE"

echo
echo "== Step 0: restore nest if broken =="
echo "(Incomplete nest (missing/.work) causes OS Error 259; restore clears it."
echo " Primary bug is failed aces+CEF unpack. Nest moves are backed up first.)"

if [[ ! -d "$INNER" && -d "$BASE/WarThunder.app.work" ]]; then
  echo "Nest missing; restoring from WarThunder.app.work..."
  backup_then_mv "$BASE/WarThunder.app.work" "$INNER" "WarThunder.app.work"
  echo "Nest restored from .work"
elif [[ ! -d "$INNER" && -d "$BASE/WarThunder.app" ]]; then
  echo "Nest missing; restoring from top-level WarThunder.app..."
  backup_then_mv "$BASE/WarThunder.app" "$INNER" "WarThunder.app"
  echo "Nest restored from top-level WarThunder.app"
elif [[ -d "$INNER" ]]; then
  echo "Nest path present - skipping."
else
  die "no WarThunder.app nest and no .work restore candidate under:
  $BASE
Stop and inspect the install layout before continuing."
fi

[[ -d "$GAME" ]] || die "expected payload directory not found at:
  $GAME
Your install layout may differ from what this script expects."

echo
echo "== Step 1: unpack CEF + aces if missing =="
echo "(Unzip preserves Gaijin Developer ID signatures from the shipped zips.)"

mkdir -p "$INNER/Contents/Frameworks"
mkdir -p "$INNER/Contents/MacOS"

if [[ ! -f "$INNER/Contents/Frameworks/cef.framework/cef" ]]; then
  echo "Unpacking CEF framework from shipped payload..."
  unzip_into "$GAME/mac_cef_framework.zip" "$INNER/Contents/Frameworks"
  unzip_into "$GAME/frameworks.zip" "$INNER/Contents/Frameworks"
  unzip_into "$GAME/mac_cef_bin.zip" "$INNER/Contents/MacOS"
  [[ -f "$INNER/Contents/Frameworks/cef.framework/cef" ]] \
    || die "CEF still missing after unzip at:
  $INNER/Contents/Frameworks/cef.framework/cef"
  echo "CEF unpacked."
else
  echo "CEF already present - skipping."
fi

if [[ ! -x "$INNER/Contents/MacOS/aces" ]]; then
  echo "Unpacking aces binary from shipped payload..."
  # shellcheck disable=SC2064
  TMP_DIR="$(mktemp -d)"
  unzip_into "$GAME/mac.zip" "$TMP_DIR"
  [[ -f "$TMP_DIR/aces" ]] || { rm -rf "$TMP_DIR"; die "mac.zip did not contain an 'aces' binary (unexpected layout)."; }
  cp "$TMP_DIR/aces" "$INNER/Contents/MacOS/"
  chmod +x "$INNER/Contents/MacOS/aces"
  rm -rf "$TMP_DIR"
  echo "aces unpacked."
else
  echo "aces already present - skipping."
fi

echo
echo "== Step 2: ad-hoc sign ONLY if a payload binary fails codesign --verify =="
echo "(Skip healthy Developer ID binaries. Blind --force ad-hoc breaks the outer seal.)"

SIGNED_ANY=0
for target in \
  "$INNER/Contents/MacOS/aces" \
  "$INNER/Contents/Frameworks/cef.framework/cef" \
  "$INNER/Contents/Frameworks/libsteam_api.dylib"
do
  if [[ -e "$target" ]] && needs_adhoc_sign "$target"; then
    echo "Ad-hoc signing (verify failed): $target"
    codesign --force --sign - "$target" || die "codesign failed for $target"
    SIGNED_ANY=1
  elif [[ -e "$target" ]]; then
    echo "Signature OK - leaving alone: $target"
  fi
done

if [[ "$SIGNED_ANY" -eq 0 ]]; then
  echo "No ad-hoc signing needed."
fi

echo
echo "== Step 3: check for a stuck partial Steam update =="

STEAMAPPS_DIR="$(dirname "$(dirname "$BASE")")"
MANIFEST="$(find "$STEAMAPPS_DIR" -maxdepth 1 -iname "appmanifest_236390.acf" 2>/dev/null | head -1 || true)"

if [[ -n "$MANIFEST" ]]; then
  echo "Found manifest: $MANIFEST"
  echo "If Steam ever tries to redownload the whole ~85GB game instead of just"
  echo "launching it, back this file up first, then check/zero these keys:"
  echo "  BytesToDownload, BytesDownloaded, BytesToStage, BytesStaged"
else
  echo "Could not auto-locate appmanifest_236390.acf - check your steamapps/ folder if needed."
fi

cat <<EOF

== Step 4: launch ==

Fully quit Steam, relaunch it, and hit Play.

Then: System Settings -> Privacy & Security -> Security -> Open Anyway
if macOS blocked the app. Do not skip that step.

If the launcher sits at ~16KB RSS with no "aces" child, that is usually still
signature trust (or missing unpack) — not a reason to reinstall.

Sanity check:

  ps -axo pid,rss,etime,command | grep -i "MacOS/aces" | grep -v grep

Real game: RSS tens/hundreds of MB and climbing. Zombie launcher: ~16KB stuck.

If Steam still will not spawn aces after Open Anyway:

  ./play-warthunder.sh "$BASE"

Nest-restore backups (if any) are under:
  $BASE/.wt-fix-backup/
EOF
